### ISSUE TITLE
Cannot perform export

### ISSUE THREAD

**Issue by bsobor** [gaborposz/VideoFritter#1] opened 2020-12-25 14:37 UTC
Whatever section of the video is selected, cannot perform expert, as throws this exception:
![image](https://user-images.githubusercontent.com/50029489/103137027-b2f78680-46c5-11eb-94b8-4432347f1404.png)

My educated guess, may be related to Ryzen and built in graphics vs. ffmpeg.
The playback of video is smooth.

Using standard GoPro Hero5 timelapse recording, only video, no audio.
**Video Information:**
- Codec: AVC1 - Native D3D9 DXVA Decoder(VLD) - AMD Radeon(TM) RX Vega 11 Graphics
- Input type: AVC1(24 bits)
- Input size: 2704 × 2028(1.33:1)
- Frame rate: 29.97

**HW:**
- Processor	AMD Ryzen 5 3400G with Radeon Vega Graphics       3.70 GHz
- Installed RAM	16,0 GB (13,9 GB usable)
- System type	64-bit operating system, x64-based processor

**OS:**
- Edition	Windows 10 Pro
- Version	20H2
- Installed on	‎2019. ‎12. ‎12.
- OS build	19042.685
- Experience	Windows Feature Experience Pack 120.2212.1070.0

**Videofritter: v0.9.0-beta**

**Comment by bsobor** [comment] 2020-12-25 15:02
Okay, tried with other GoPro Hero5 recordings (non-timelapse) also, did not work either.
Tried with drone footage from @gaborposz, that worked.
Tried with video from my Sony camera, that worked also.

**Comment by bsobor** [comment] 2020-12-26 18:41
As requested a sample video from GoPro Hero5 is available here:
https://drive.google.com/file/d/1wOovIF4FEMxDuoGYW4RjoGhqCwKmfREe/view?usp=sharing
It is GOPR0841.MP4 from Ireland.

Based on spot test every GoPro Hero5 recording has the incompatibility issue.

**Comment by gaborposz** [comment] 2021-01-17 09:59
The problem is the following:

There are multiple media streams in the file. Some of them are video, some are audio, but there are also other kind of streams, like data streams with recorded sensor (gyroscope, GPS, etc.) data.

Unfortunately the [ffmpeg](https://ffmpeg.org/) library (that I use to process the video files) does not support coping such streams, or at least I could not find any way to do it. (See my stackoverflow question [here](https://stackoverflow.com/questions/65468853/how-to-copy-data-streams-with-ffmpeg).)

So for the moment I will simply exclude all streams except audio and video. Of course it means that other stream will be missing from the processed file :(

In the future I will probably get back to this, and look for way to copy all the streams, not just audio and video.

**Comment by gaborposz** [comment] 2021-01-17 11:50
Fixed with [357d56358e02f13ef55ad700fde2143c6f74b7df](https://github.com/gaborposz/VideoFritter/commit/357d56358e02f13ef55ad700fde2143c6f74b7df).

I will close this issue, and create a separate one for supporting other kind of streams.

**Closed as completed by gaborposz** 2021-01-17 11:50 UTC
Labels: bug
